package com.mycompany.transfersystem.entity.enums;

public enum AiToolName {
    GET_MY_TRANSACTION_STATUS,
    GET_MY_WALLET_SUMMARY,
    GET_MY_KYC_STATUS,
    GET_NEAREST_BRANCHES,
    CREATE_DISPUTE_DRAFT,
    GET_BRANCH_QUEUE_SUMMARY,
    GET_BRANCH_LIQUIDITY_FORECAST,
    GET_CASHIER_SHIFT_SUMMARY,
    GET_PLATFORM_REVENUE_SUMMARY,
    GET_AML_CRITICAL_SUMMARY,
    GET_TRADING_PORTFOLIO_SUMMARY,
    GET_MARKET_QUOTE,
    CREATE_PRICE_ALERT_DRAFT
}
