ALTER TABLE translations ADD COLUMN IF NOT EXISTS locale VARCHAR(10);

DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'translations' AND column_name = 'language_code'
    ) THEN
        EXECUTE 'UPDATE translations SET locale = COALESCE(locale, language_code, ''en'') WHERE locale IS NULL';
        EXECUTE 'ALTER TABLE translations ALTER COLUMN language_code DROP NOT NULL';
    ELSE
        UPDATE translations SET locale = COALESCE(locale, 'en') WHERE locale IS NULL;
    END IF;
END $$;

ALTER TABLE translations ALTER COLUMN locale SET NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_translations_locale_message_key ON translations(locale, message_key);

INSERT INTO translations(locale, message_key, message_value) VALUES
('en', 'app.name', 'ALMUKHTAR Elite'),
('en', 'common.language', 'Language'),
('en', 'common.direction', 'ltr'),
('en', 'common.continue', 'Continue'),
('en', 'common.cancel', 'Cancel'),
('en', 'common.confirm', 'Confirm'),
('en', 'common.save', 'Save'),
('en', 'common.close', 'Close'),
('en', 'common.search', 'Search'),
('en', 'common.amount', 'Amount'),
('en', 'common.currency', 'Currency'),
('en', 'common.status', 'Status'),
('en', 'common.branch', 'Branch'),
('en', 'common.fees', 'Fees'),
('en', 'common.total', 'Total'),
('en', 'auth.login.title', 'Sign in'),
('en', 'auth.username', 'Username'),
('en', 'auth.password', 'Password'),
('en', 'auth.login.submit', 'Sign in'),
('en', 'auth.error.invalid', 'Username or password is incorrect.'),
('en', 'home.balance', 'Wallet balance'),
('en', 'home.quickTransfer', 'Send hawala'),
('en', 'home.scanQr', 'Scan QR'),
('en', 'home.payBill', 'Pay a bill'),
('en', 'home.trade', 'Trading'),
('en', 'transfer.title', 'Send money'),
('en', 'transfer.senderBranch', 'Sender branch'),
('en', 'transfer.receiverBranch', 'Receiver branch'),
('en', 'transfer.receiverName', 'Receiver name'),
('en', 'transfer.receiverPhone', 'Receiver phone'),
('en', 'transfer.releaseCode', 'Release code'),
('en', 'transfer.cleanPayout', 'Receiver gets the full amount. Fees are paid by the sender branch.'),
('en', 'transfer.pending', 'Transfer is pending until the release code is verified.'),
('en', 'transfer.completed', 'Transfer completed successfully.'),
('en', 'transfer.failed', 'Transfer failed. Please try again or contact the branch.'),
('en', 'qr.title', 'Smart-Bridge QR'),
('en', 'qr.instructions', 'Show this QR to the cashier at any ALMUKHTAR branch.'),
('en', 'qr.expired', 'This QR code has expired. Please request a new one.'),
('en', 'qr.used', 'This QR code was already used.'),
('en', 'wallet.title', 'My wallet'),
('en', 'wallet.topup', 'Top up wallet'),
('en', 'wallet.exchange', 'Exchange currency'),
('en', 'wallet.frozen', 'Wallet is temporarily frozen. Contact support.'),
('en', 'kyc.title', 'Identity verification'),
('en', 'kyc.uploadId', 'Upload ID document'),
('en', 'kyc.selfie', 'Upload selfie'),
('en', 'kyc.pending', 'Your verification is under review.'),
('en', 'merchant.pay', 'Merchant payment'),
('en', 'bills.title', 'Bills and top-ups'),
('en', 'trading.title', 'Trading account'),
('en', 'trading.marketOrder', 'Market order'),
('en', 'trading.limitOrder', 'Limit order'),
('en', 'loan.title', 'Small loans'),
('en', 'loan.apply', 'Apply for a loan'),
('en', 'security.biometricRequired', 'Biometric confirmation is required for this transaction.'),
('en', 'security.passcodeRequired', 'Enter the 6-digit release code.'),
('en', 'offline.queued', 'Transaction saved offline and will sync when internet returns.'),
('en', 'offline.synced', 'Offline transaction synced successfully.'),
('en', 'support.contactBranch', 'Contact your branch for help.'),
('ar', 'app.name', 'المختار إيليت'),
('ar', 'common.language', 'اللغة'),
('ar', 'common.direction', 'rtl'),
('ar', 'common.continue', 'متابعة'),
('ar', 'common.cancel', 'إلغاء'),
('ar', 'common.confirm', 'تأكيد'),
('ar', 'common.save', 'حفظ'),
('ar', 'common.close', 'إغلاق'),
('ar', 'common.search', 'بحث'),
('ar', 'common.amount', 'المبلغ'),
('ar', 'common.currency', 'العملة'),
('ar', 'common.status', 'الحالة'),
('ar', 'common.branch', 'الفرع'),
('ar', 'common.fees', 'الأجور'),
('ar', 'common.total', 'المجموع'),
('ar', 'auth.login.title', 'تسجيل الدخول'),
('ar', 'auth.username', 'اسم المستخدم'),
('ar', 'auth.password', 'كلمة السر'),
('ar', 'auth.login.submit', 'دخول'),
('ar', 'auth.error.invalid', 'اسم المستخدم أو كلمة السر غير صحيحة.'),
('ar', 'home.balance', 'رصيد المحفظة'),
('ar', 'home.quickTransfer', 'إرسال حوالة'),
('ar', 'home.scanQr', 'مسح QR'),
('ar', 'home.payBill', 'دفع فاتورة'),
('ar', 'home.trade', 'التداول'),
('ar', 'transfer.title', 'إرسال حوالة'),
('ar', 'transfer.senderBranch', 'فرع الإرسال'),
('ar', 'transfer.receiverBranch', 'فرع الاستلام'),
('ar', 'transfer.receiverName', 'اسم المستلم'),
('ar', 'transfer.receiverPhone', 'رقم المستلم'),
('ar', 'transfer.releaseCode', 'رمز التسليم'),
('ar', 'transfer.cleanPayout', 'المستلم يقبض المبلغ كامل. الأجور محسوبة على فرع الإرسال.'),
('ar', 'transfer.pending', 'الحوالة معلقة لحتى يتم التأكد من رمز التسليم.'),
('ar', 'transfer.completed', 'تمت الحوالة بنجاح.'),
('ar', 'transfer.failed', 'ما تمت الحوالة. حاول مرة تانية أو راجع الفرع.'),
('ar', 'qr.title', 'QR الاستلام الذكي'),
('ar', 'qr.instructions', 'فرجي هذا الرمز للكاشير بأي فرع من فروع المختار.'),
('ar', 'qr.expired', 'انتهت صلاحية رمز QR. اطلب رمز جديد.'),
('ar', 'qr.used', 'رمز QR مستخدم من قبل.'),
('ar', 'wallet.title', 'محفظتي'),
('ar', 'wallet.topup', 'تعبئة المحفظة'),
('ar', 'wallet.exchange', 'تصريف عملة'),
('ar', 'wallet.frozen', 'المحفظة موقوفة مؤقتا. تواصل مع الدعم.'),
('ar', 'kyc.title', 'تأكيد الهوية'),
('ar', 'kyc.uploadId', 'ارفع صورة الهوية'),
('ar', 'kyc.selfie', 'ارفع صورة سيلفي'),
('ar', 'kyc.pending', 'طلب التحقق قيد المراجعة.'),
('ar', 'merchant.pay', 'دفع لتاجر'),
('ar', 'bills.title', 'الفواتير والتعبئة'),
('ar', 'trading.title', 'حساب التداول'),
('ar', 'trading.marketOrder', 'أمر سوق'),
('ar', 'trading.limitOrder', 'أمر محدد'),
('ar', 'loan.title', 'قروض صغيرة'),
('ar', 'loan.apply', 'طلب قرض'),
('ar', 'security.biometricRequired', 'مطلوب تأكيد بالبصمة أو الوجه لهذه العملية.'),
('ar', 'security.passcodeRequired', 'أدخل رمز التسليم المؤلف من 6 أرقام.'),
('ar', 'offline.queued', 'تم حفظ العملية بدون إنترنت، وبتتزامن أول ما يرجع الاتصال.'),
('ar', 'offline.synced', 'تمت مزامنة العملية بنجاح.'),
('ar', 'support.contactBranch', 'راجع فرعك للمساعدة.')
ON CONFLICT (locale, message_key) DO UPDATE SET message_value = EXCLUDED.message_value;

INSERT INTO translations(locale, message_key, message_value)
SELECT 'ar-SY', message_key, message_value FROM translations WHERE locale = 'ar'
ON CONFLICT (locale, message_key) DO UPDATE SET message_value = EXCLUDED.message_value;
